In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [2]:
df = pd.read_csv("extracted_data/sha_disbursements_master_file.csv", index_col=False)

In [3]:
df.shape

(34161, 7)

In [4]:
df.head()

,vendor_name,claims,amount,report_month,report_year,schedule,source_pdf
0,"ST CATHERINE'S ICHUNI MISSION HOSPITAL 4 ,",NaN,786479.99,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf
1,"TEMBEZI MEDICAL SERVICES 1 ,",NaN,859005.76,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf
2,"USHIRIKA DISPENSARY 1 ,",NaN,576842.10,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf
3,"TARACHA HEALTH CENTRE 1 ,",NaN,518997.64,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf
4,"Hunter Medical Center 1 ,",NaN,1810.76,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf

In [5]:
df.describe()

       claims        amount  report_year      schedule
count     0.0  3.416100e+04      34161.0  34161.000000
mean      NaN  1.324319e+06       2025.0      1.183660
std       NaN  5.255641e+07          0.0      0.491548
min       NaN  0.000000e+00       2025.0      1.000000
25%       NaN  2.032000e+04       2025.0      1.000000
50%       NaN  9.000000e+04       2025.0      1.000000
75%       NaN  3.660800e+05       2025.0      1.000000
max       NaN  6.629671e+09       2025.0      4.000000

In [6]:
df = df.drop(columns=["claims"])

In [7]:
df = df[~df['vendor_name'].str.contains(r'page', case=False, na=False)]
df['vendor_name'] = df['vendor_name'].str.lower().str.title()

df = df.sort_values(by="vendor_name").reset_index(drop=True)
df['vendor_name'] = df['vendor_name'].replace(',', 'Unnamed Facility')
df = df[df['vendor_name'].str.strip().str.lower() != 'total']
df = df[df['vendor_name'].str.strip().str.lower() != 'grand total']

In [8]:
# remove a leading number (and surrounding punctuation/spaces) from facility_name
df['vendor_name'] = (
    df['vendor_name']
      .str.replace(r'^\s*[\(\[]?\s*\d+[a-zA-Z]?[\)\].:-]*\s*', '', regex=True)
      .str.replace(r'\s+', ' ', regex=True)
      .str.strip()
)
df['vendor_name'] = df['vendor_name'].str.replace(r'\s*(?:[-–—/()]|\bNo\.?\b|#)*\s*\d+[A-Za-z]?\s*,?\s*$', '', regex=True).str.replace(r'\s{2,}', ' ', regex=True).str.strip().str.rstrip('-–—.,:;()')

In [9]:
df[df['vendor_name'].str.contains(r'\d+\s*,?\s*$', na=False)].shape

(8, 6)

In [10]:
df['year_month'] = pd.to_datetime(
    df['report_year'].astype(str) + '-' + df['report_month'],
    format='%Y-%B'
).dt.strftime('%b-%Y')

In [11]:
df[df['vendor_name'].str.strip().str.lower() == 'grand total']

Empty DataFrame
Columns: [vendor_name, amount, report_month, report_year, schedule, source_pdf, year_month]
Index: []

In [12]:
df['vendor_name'] = (
    df['vendor_name'].astype(str).str.normalize("NFKC").str.lower()
      .str.replace(r"[’`]", "'", regex=True)                               # unify apostrophes
      .str.replace(r"\bmurang[\'’` ]?a\b", "murang'a", regex=True)         # muranga/murang a -> murang'a
      .str.replace(r"\brefferal\b", "referral", regex=True)                # fix "refferal"
      .str.replace(r"\bhealthcarelimited\b", "healthcare limited", regex=True)  # split stuck words
      .str.replace(r"\s*-\s*", " - ", regex=True)                          # normalize hyphen spacing
      .str.replace(r"\s+", " ", regex=True).str.strip()
      .str.title()
      .str.replace(r"\bGvs\b", "GVS", regex=True)                          # restore acronyms
      .str.replace("Murang'A", "Murang'a", regex=False)                    # fix title-case artifact
)

In [13]:
df['vendor_name'] = df['vendor_name'].str.replace(r'(?i)\bdispensa[\W_]*r[\W_]*y\b', 'dispensary', regex=True).str.replace(r'\s+', ' ', regex=True).str.strip().str.title()

In [14]:
df['vendor_name'] = df['vendor_name'].str.replace(
    r'(?i)\bhealth service\b', 'health services', regex=True
).str.replace(r'\s+', ' ', regex=True).str.strip().str.title()

In [15]:
df['vendor_name'] = (
    df['vendor_name']
      .str.replace(r'(?i)\bL\s*I\s*M\s*I\s*T\s*E\s*D?\b', 'Limited', regex=True)
      .str.replace(r'\s+', ' ', regex=True)
      .str.strip()
      .str.title()
)

In [16]:
df[df['vendor_name'].str.contains(r'advanced care', case=False, na=False)]["vendor_name"]

1472    Advanced Care Diagnostic And Renal Dialysis Limited
1767    Advanced Care Diagnostic And Renal Dialysis Limited
1768    Advanced Care Diagnostic And Renal Dialysis Limited
3579    Advanced Care Diagnostic And Renal Dialysis Limited
8061    Advanced Care Diagnostic And Renal Dialysis Limited
8062    Advanced Care Diagnostic And Renal Dialysis Limited
Name: vendor_name, dtype: object

In [17]:
df[df["vendor_name"] == "Tumticha Medical Centre Limited"]

,vendor_name,amount,report_month,report_year,schedule,source_pdf,year_month
32929,Tumticha Medical Centre Limited,123200.0,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf,Apr-2025
32930,Tumticha Medical Centre Limited,178722.7,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf,Apr-2025
32931,Tumticha Medical Centre Limited,224000.0,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf,Apr-2025
32932,Tumticha Medical Centre Limited,19680.0,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf,Apr-2025
32933,Tumticha Medical Centre Limited,5600.0,April,2025,1,SHA_PAID_FACILITIES_APRIL_2025.pdf,Apr-2025

In [18]:
df.shape

(34065, 7)

In [19]:
df.head(100)

,vendor_name,amount,report_month,report_year,schedule,source_pdf,year_month
0,,2.085357e+07,July,2025,1,SHA_PAYMENTS_JULY_2025_1.pdf,Jul-2025
1,3Rd Park Hospital Limited,3.360000e+04,July,2025,4,SHA_PAYMENTS_JULY_2025_4.pdf,Jul-2025
2,3Rd Park Hospital Limited,1.310400e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
3,A.C.K. Maseno Hospital,1.895040e+06,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
4,A.I.C Githumu Mission Hospital,4.368000e+04,August,2025,2,SHA_PAYMENTS_AUGUST_2025_2.pdf,Aug-2025
5,A.I.C Githumu Mission Hospital,5.370000e+05,July,2025,3,SHA_PAYMENTS_JULY_2025_3.pdf,Jul-2025
6,Kenyatta National Hospital,3.414919e+08,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
7,Abidha Health Centre,6.720000e+03,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
8,Ack Mt Kenya Hospital Mwea,1.718080e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
9,Afyaline Salgaa Medical Centre,1.344000e+04,August,2025,2,SHA_PAYMENTS_AUGUST_2025_2.pdf,Aug-2025
10,Aic Kijabe Hospital,2.206508e+07,July,2025,3,SHA_PAYMENTS_JULY_2025_3.pdf,Jul-2025
11,Aic Litein Hospital,3.387600e+06,July,2025,4,SHA_PAYMENTS_JULY_2025_4.pdf,Jul-2025
12,Top Hill Brain And Spine Hospital,5.699855e+07,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
13,Barika Medical Centre Limited,3.651200e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
14,Blue Ridge Medical Ltd - Kisumu,1.014500e+06,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
15,Consolata Hospital Kyeni,3.136000e+05,August,2025,2,SHA_PAYMENTS_AUGUST_2025_2.pdf,Aug-2025
16,Gaichanjiru Catholic Hospital,2.794400e+05,July,2025,4,SHA_PAYMENTS_JULY_2025_4.pdf,Jul-2025
17,Goodwill Cottage Hospital,7.612640e+06,July,2025,3,SHA_PAYMENTS_JULY_2025_3.pdf,Jul-2025
18,Komarock Modern Healthcare Utawala,1.241549e+07,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
19,Cliss Medical Centre,8.736000e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
20,Moi Voi County Referral Hospital,1.025100e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
21,Pipeline Modern Hospital,5.615680e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
22,Moi'S Bridge Mission Health Centre,1.568000e+04,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
23,Plainsview Nursing Home Ltd,1.351990e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
24,Senye Medical Centre,8.721200e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
25,Mokowe Health Centre,6.384000e+04,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
26,Plaza Specialist Hospital Limited,1.631350e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
27,Summit Medicare Ltd - Chepilat,8.701600e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
28,Bute Sub County Hospital,8.699200e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
29,Mokowe Health Centre,3.360000e+04,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
30,Pope Benedict Xvi Hospital,1.223407e+07,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
31,Ikutha Medicare Clinic,8.688000e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
32,Mokowe Medical Centre - Faza,4.368000e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
33,Poplar Hospital Ltd,1.344000e+04,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
34,Medina Medicare Hospital Limited - Wajir,8.680000e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
35,Mokowe Medical Centre - Faza,9.184000e+04,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
36,Port Florence Community Hospital - Awasi,2.195200e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
37,Molo Sub - County Hospital,6.921600e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
38,Nashad Nursing Home,8.668800e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
39,Port Florence Community Hospital - Mega Plaza Limited,2.240000e+04,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
40,Molo Sub - County Hospital,1.310400e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
41,Musab Bin Umeir Nursing Home Limited,8.668800e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
42,Port - Reitz Sub County Hospital,7.746500e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
43,Mombasa Cancer Centre,1.072340e+07,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
44,Precious Hospital,2.867200e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
45,Toric'S Nursing Home,8.668800e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
46,Mandera West Nursing Home Limited,8.635200e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
47,Mombasa Cancer Centre,2.867266e+06,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
48,Premier Hospital,5.191200e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
49,Baringo County Referral Hospital,6.407710e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
50,Bokoli Sub County Hospital,1.155840e+06,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
51,Consolata Hospital Mathari,1.254400e+05,August,2025,2,SHA_PAYMENTS_AUGUST_2025_2.pdf,Aug-2025
52,Galilee Hospital Kitale Limited,4.816000e+05,July,2025,4,SHA_PAYMENTS_JULY_2025_4.pdf,Jul-2025
53,Grace Park Medical Centre,3.259200e+06,July,2025,3,SHA_PAYMENTS_JULY_2025_3.pdf,Jul-2025
54,Suba Sub - County Hospital,1.224688e+07,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
55,Mombasa Catholic Cbhc Services,1.612800e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
56,Prime Gala Medical Centre,1.043840e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
57,Tarasaa Medical Centre Limited,8.624000e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
58,Bashey Nursing Home Limited,8.624000e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
59,Mombasa Hospital Association,1.278000e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
60,Primrose Rehab & Wellness Center,4.032000e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
61,Mombasa Hospital Association,1.704000e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
62,Muntasir Nursing Home,8.601600e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
63,Prof.Lucas Community Health System,6.115200e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
64,Healthy Lifestyles Weight Loss Centre Limited,8.600000e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
65,Mosoriot Sub - County Hospital,3.830400e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
66,Progress Medical Services Annex,8.288000e+04,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
67,Breetons Medical Centre Limited,8.579200e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
68,Mosoriot Sub - County Hospital,1.108800e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
69,Provincial General Hospital Annex Nakuru,1.679440e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
70,Mother & Child Hospital,4.875000e+04,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
71,Prudent Cottage Hospital,2.559500e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
72,St Pauls Emusonga Medical Centre,8.579200e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
73,Mother Amadea Mission Hospital,4.015200e+06,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
74,Pumwani Maternity And Referral Hospital,2.399464e+07,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
75,Takaba Sub - County Hospital,8.562400e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
76,An Najah Medical Care Limited,8.556800e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
77,Mother Amadea Mission Hospital,4.534400e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
78,Pwani Maternity And Nursing Home,6.944000e+04,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
79,Caregivers Community Hospital,8.553600e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
80,Mother And Child Hospital,9.798000e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
81,Pynet Healthcare Adungosi,6.496000e+04,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
82,Holy Family Hospital Nangina,8.531200e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
83,Mother And Child Hospital,1.810500e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
84,Pynet Healthcare Limited,3.046400e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
85,Baxnan Medical Centre,2.665600e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
86,Bokoli Sub County Hospital,3.392800e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
87,Consolata Hospital Nkubu,4.116000e+05,August,2025,2,SHA_PAYMENTS_AUGUST_2025_2.pdf,Aug-2025
88,Garissa Doctors Plaza,3.605320e+06,July,2025,4,SHA_PAYMENTS_JULY_2025_4.pdf,Jul-2025
89,Grand Royalcare Medical Clinic Limited,8.302560e+06,July,2025,3,SHA_PAYMENTS_JULY_2025_3.pdf,Jul-2025
90,St. Anthony Catholic Hospital,1.218092e+07,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
91,Burnt Forest Sub - County Hospital,8.525500e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
92,Mother Angela Huruma Hospital,2.150400e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
93,Qaran Hospital Limited,7.392000e+04,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
94,Lodwar Tumaini Medical Services,8.524500e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025
95,Mother Angela Huruma Hospital,3.024000e+04,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
96,Qarsahama Dispensary,5.200000e+05,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
97,Mother Francisca Mission Maternity And Health Centre,3.830400e+05,July,2025,1,SHA_PAID_FACILITIES_JULY_2025.pdf,Jul-2025
98,Qasims Hospital Limited,4.019680e+06,August,2025,1,SHA_PAYMENTS_AUGUST_2025_1.pdf,Aug-2025
99,South C Dialysis Centre Ltd,8.520000e+05,June,2025,2,SHA_PAID_FACILITIES_JUNE_2025-2.pdf,Jun-2025

In [20]:
df.to_csv("extracted_data/sha_disbursements_master.csv", index=False)